# Generated by Django 3.2.7 on 2021-09-11 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapthing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=70)),
            ],
        ),
        migrations.RenameField(
            model_name='event',
            old_name='visibility',
            new_name='public',
        ),
        migrations.RemoveField(
            model_name='event',
            name='attendants',
        ),
        migrations.AddField(
            model_name='event',
            name='max_number_people',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='min_number_people',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Attend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associated_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapthing.event')),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapthing.user')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapthing.user'),
        ),
    ]
