# Generated by Django 3.2.7 on 2021-09-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapthing', '0002_auto_20210911_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(verbose_name='start date'),
        ),
    ]
