# Generated by Django 3.2.7 on 2021-09-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapthing', '0004_auto_20210911_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attend',
            name='attendee',
        ),
        migrations.RemoveField(
            model_name='event',
            name='creator',
        ),
        migrations.AddField(
            model_name='attend',
            name='attendee_name',
            field=models.CharField(default='Attendee', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='creator_name',
            field=models.CharField(default='Creator', max_length=200),
            preserve_default=False,
        ),
    ]
